apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.network/webnet: "true"
    io.kompose.service: web
  name: web
spec:
  containers:
  - image: pepesan/app-python:latest
    name: web
    ports:
    - containerPort: 5000
    resources:
      limits:
        cpu: 100m
        memory: "52428800"
  restartPolicy: OnFailure
status: {}
