version: '3'
services:
  web:
    image: $DOCKER_IMAGE_USER/$DOCKER_IMAGE_NAME:latest
    restart: always
    ports:
      - "$NGINX_DEFAULT_PORT:80"
    volumes:
     - ./app:/usr/share/nginx/html
    networks:
      - webnet
networks:
  webnet: