version: '3.3'

services:
   db:
     image: mysql:5.7.30
     volumes:
       - db_data_wp:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: rootwordpress
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8001:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: rootwordpress
       WORDPRESS_DB_NAME: wordpress
volumes:
    db_data_wp: {}
