version: '3.3'

services:
   db:
     image: mariadb:10.5.8-focal
     container_name: db-pro
     volumes:
       - ./volumes/db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: rootwordpress
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     container_name: wp-pro
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: rootwordpress
       WORDPRESS_DB_NAME: wordpress
