version: "3"
services:
  web:
    image: pepesan/mi-tomcat8-jdk8:latest
    container_name: mi-tomcat
    ports:
      - "8000:8080"
    volumes:
      - "./conf:/usr/local/tomcat/conf"
      - "./logs:/usr/local/tomcat/logs"
    networks:
      - webnet
networks:
  webnet: